version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/blog
    steps:
      - checkout
      - run: 
         command: |
          npm install
          npm install -g hexo-cli
          hexo g
      - run: sudo apt-get update && sudo apt-get install rsync
      - deploy:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              rsync -avce ssh build $SSH_USER@$SSH_IP:/root/blog/
            else
              echo "Not master branch, dry run only"
            fi
      - run: echo 'deploy successfully'
workflows:
  version: 2
  deploy:
    jobs:
      - build
  