version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/blog
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "f9:a5:6b:ad:73:78:5b:50:ab:e7:30:ca:03:50:8d:59"
      - run: echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
      - deploy:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              ssh root@101.201.125.78
              cd /root/blog/
              git clone -f
              hexo clean
              hexo g
            else
              echo "Not master branch, dry run only"
            fi
      - run: echo 'deploy successfully'
workflows:
  version: 2
  deploy:
    jobs:
      - build
  